# Generated by Django 4.2.3 on 2023-07-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galary', '0002_userprofile_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='defoult', upload_to='profile_images/'),
        ),
    ]
